from . import res_partner
from . import product_category
from . import product_template
from . import product_product
from . import stock_quant
from . import sale_cart
from . import sale_order
from . import account_move
from . import shopify_client
from . import shopify_config
from . import shopify_sync
from . import ai_models