{
    'name': 'ShopFlow',
    'version': '17.0.1.0.0',
    'category': 'Sales/eCommerce',
    'summary': 'Unified commerce and ERP platform with Shopify and AI automation',
    'author': 'Hnin',
    'depends': [
        'base',
        'mail',
        'sale',
        'account',
        'stock',
        'product',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/cron_jobs.xml',
        'views/shopify_config_views.xml',
        'views/shopify_cart_views.xml',
        'views/shopify_webhook_event_views.xml',
        'views/shopify_ai_recommendation_views.xml',
        'views/shopify_ai_lead_score_views.xml',
        'views/shopify_ai_chat_session_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/shopify_product_sync_wizard_views.xml',
        'views/sale_order_views.xml',
    ],
    'test': ['tests/test_integration.py'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}